### ISSUE TITLE
Investment Value 

### ISSUE THREAD

**Issue by vamseeachanta** [samdansk2/assethold#10]
Objective is to calculate the advantages or otherwise of Cash vs Stocks
- [x]  Calculate simple interest and compound interest
- [x] Calculate ticker profit for multiple years

**Comment by vamseeachanta** [comment]
Hypothetical scenarios:
- 2024-01-01: 1000 ... year. On a monthly basis, what is the value?

**Comment by samdansk2** [comment]
@vamseeachanta Hello sir , 

- prepared configuration file with all parameters 
- created a new class called TickerProfit
- changed interval monthly to daily 
please see below :

**Comment by vamseeachanta** [comment]
- If a user invests 100 every month (start of the month)
- Calculate the total money invested (if for 12 months, 12*100)
- Calculate the total value (every month value)
- calculate overall value (add all values)
- calculate overall profit (final value/total money * 100)

calculate this for every day

**Comment by samdansk2** [comment]
@vamseeachanta 
Hello sir ,
Done doing for single and monthly investment , please see below:
https://github.com/samdansk2/assethold/tree/first_pass_run/src/assethold/tests/test_data/analysis/Portfolio/results/Data

**Comment by samdansk2** [comment]
see how our profit calculation compares against the below package
https://github.com/pmorissette/ffn

If possible, use packages already out there.

What we have done so far is great to understand what our calculations mean. However, we need to utilize other standard packages. The main strengths of python is to leverage packages out there.

A library we should consider to contributing to:
https://github.com/pmorissette/bt

**Comment by samdansk2** [comment]
@vamseeachanta 
please review the below method using Ffn library sir and also it's architecture
https://github.com/samdansk2/assethold/blob/first_pass_run/docs/financial_function_Ffn.png
https://github.com/samdansk2/assethold/blob/first_pass_run/src/assethold/modules/stocks/investment_value_ffn.py

**Comment by vamseeachanta** [comment]
@samdansk2 , please show a comparison of the numbers as a test so that we can choose one. 

Please do a deepdiff yaml file comparison for the test.

**Comment by samdansk2** [comment]
@vamseeachanta 

hello sir , now you can see below how returns percentage vary from ticker to ticker 
https://github.com/samdansk2/assethold/blob/first_pass_run/docs/modules/portfolio/portfolio_ffn_vs_assethold_calc.md

**Comment by vamseeachanta** [comment]
can you find out from ffn documentation if it considers dividends and close out this issue. 

Also, while at it, create check boxes for each topic so we know what topics we are tackling in each story/issue.

**Comment by samdansk2** [comment]
Evening sir ,
Basically ffn library retrieves data from Yahoo finance . 
ffn consider dividends , because 'Adj Close' values and 'Close' values both are different .

It indicates that Yahoo Finance adjusts for dividends, and ffn uses these adjusted prices in its calculations.

**Comment by samdansk2** [comment]
can i close this issue out sir ?

**Comment by vamseeachanta** [comment]
brilliant research. You can close this issue.
