### ISSUE TITLE
Repository Improvements

### ISSUE THREAD

**Issue by vamseeachanta** [samdansk2/assethold#3]
- Put legacy codes into a dedicated folder
- Repository name.

**Comment by samdansk2** [comment]
@vamseeachanta 
Moved all legacy scripts into one folder sir , 
I didn't found proper name for our repo , so we should rename it as 'assethold'

**Comment by samdansk2** [comment]
There is a settings options missing for repository in GitHub sir

**Comment by samdansk2** [comment]
@vamseeachanta Hello sir , Regarding Repository name  assethold ,

- Do I need to change the all folder names inside the repo , ex: src/stockhold , 
- name in the environment.yml ( dev_tools )
- pyproject.toml - project , scripts name ( entry point )
- Readme in github

**Comment by vamseeachanta** [comment]
@samdansk2 , yes. You have to change. Easiest way is to "search and replace". 
- Check that the pipeline tests pass etc.
- Check that the self-install works 

We will fix rest as we encounter errors.

**Comment by samdansk2** [comment]
@vamseeachanta Done all setting up sir ,

- Changed all occurences of stockhold ,
- Self- installation also successful including for assetutilities ,
- All tests are running as usual .
