### ISSUE TITLE
Program | General Improvements

### ISSUE THREAD

**Issue by vamseeachanta** [samdansk2/assethold#6]
- transition from matplotlib to plotly charts for interactive charts
- Duration from yml file
  - ~~start date and end date automatically populate from duration~~
- ~~Remove pandas warnings. Search and fix them. (See below)~~
- ~~debug vs. info~~
- ~~Use Colorama for printing text (positive messages green, negative messages red).~~

**Comment by vamseeachanta** [comment]
![image](https://github.com/user-attachments/assets/c37b8fe3-1f9e-4910-b6d4-650ecfbdcce3)

**Comment by samdansk2** [comment]
> * Duration from yml file
>   
>   * start date and end date automatically populate from duration
> * Remove pandas warnings. Search and fix them. (See below)
> * debug vs. info
> * Use Colorama for printing text (positive messages green, negative messages red).

@vamseeachanta 
Fixed following sir : 

- Duration from yaml 
- Pandas warnings in teh terminal 
- debug vs info
